### Assumptions
1. No outliers in test dataset --> train set was representative enough for test set
2. Daily differences are negligible: I've compressed everything into 14 days of features

In [59]:
# Data manipulation
import pandas as pd 
import numpy as np

# Loading Model
import pickle

# For Prediction
from sklearn.metrics import mean_squared_error, r2_score


### Reading Data

In [60]:
# Load your data here (assume already split into test X and test Y:
# Assume test_X dataset has exactly 14 days worth of data points
df_x = pd.read_csv('data/yourXdata.csv')
df_y = pd.read_csv('data/yourYdata.csv')

oneHot_time_x = pd.read_csv('data/oneHotXdata.csv', index_col = 'Unnamed: 0')
oneHot_time_y = pd.read_csv('data/oneHotYdata.csv', index_col = 'Unnamed: 0')
df_x.head()

geohash6  day timestamp    demand
0   qp0d0k    1      9:45  0.002938
1   qp093q    1      9:45  0.025675
2   qp03xr    1      9:45  0.117869
3   qp0999    1      9:45  0.058613
4   qp03x3    1      9:45  0.107142

### Pre-processing

In [61]:
# Convert timestamp to float

df_x['timestamp_float'] = pd.to_datetime(df_x['timestamp'], format='%H:%M').dt.hour + pd.to_datetime(df_x['timestamp'], format='%H:%M').dt.minute/60.0
df_y['timestamp_float'] = pd.to_datetime(df_y['timestamp'], format='%H:%M').dt.hour + pd.to_datetime(df_y['timestamp'], format='%H:%M').dt.minute/60.0

df_x = df_x.drop(['timestamp'], axis=1)
df_y = df_y.drop(['timestamp'], axis=1)

In [62]:
# Assume all possible geo-hashes are there in X
# This cell converts our data to a m by n matrix, 
# where m is the total number of possible geohashes 
# and n is the number of timestamps sequentially ordered
# Extracting information by time-stamp to get features by timestamp
# Create list, then keep appending to it to form a list of lists

oneHot_x_time_col = oneHot_time_x.columns.to_list() # artificial df columns to list
oneHot_geohash_col = oneHot_time_x.T.columns.to_list()
testX_masterList = []

timeIndex = 0.0
dayIndex = 1
#dataIndex = 0

while (dayIndex <= 14):
    timeIndex = 0
    while(timeIndex < 24): # to parse every timestamp possible   
        subListY = [0]*len(oneHot_time_x.T.columns)
        df_short = df_x[(df_x.day == dayIndex) & (df_x.timestamp_float == timeIndex)]
        for row in df_short.itertuples():        
            indexCol = oneHot_geohash_col.index(row.geohash6)
            elemY = row.demand
            
            subListY[indexCol] = elemY

            #oneHot_transposed.at[indexCol,indexRow] = row.demand
        print("Time Done", timeIndex)
        timeIndex += 0.25
        testX_masterList.append(subListY)
    print("Day Done", dayIndex)
    dayIndex += 1

Time Done 0
Time Done 0.25
Time Done 0.5
Time Done 0.75
Time Done 1.0
Time Done 1.25
Time Done 1.5
Time Done 1.75
Time Done 2.0
Time Done 2.25
Time Done 2.5
Time Done 2.75
Time Done 3.0
Time Done 3.25
Time Done 3.5
Time Done 3.75
Time Done 4.0
Time Done 4.25
Time Done 4.5
Time Done 4.75
Time Done 5.0
Time Done 5.25
Time Done 5.5
Time Done 5.75
Time Done 6.0
Time Done 6.25
Time Done 6.5
Time Done 6.75
Time Done 7.0
Time Done 7.25
Time Done 7.5
Time Done 7.75
Time Done 8.0
Time Done 8.25
Time Done 8.5
Time Done 8.75
Time Done 9.0
Time Done 9.25
Time Done 9.5
Time Done 9.75
Time Done 10.0
Time Done 10.25
Time Done 10.5
Time Done 10.75
Time Done 11.0
Time Done 11.25
Time Done 11.5
Time Done 11.75
Time Done 12.0
Time Done 12.25
Time Done 12.5
Time Done 12.75
Time Done 13.0
Time Done 13.25
Time Done 13.5
Time Done 13.75
Time Done 14.0
Time Done 14.25
Time Done 14.5
Time Done 14.75
Time Done 15.0
Time Done 15.25
Time Done 15.5
Time Done 15.75
Time Done 16.0
Time Done 16.25
Time Done 16.5
Time

Time Done 16.5
Time Done 16.75
Time Done 17.0
Time Done 17.25
Time Done 17.5
Time Done 17.75
Time Done 18.0
Time Done 18.25
Time Done 18.5
Time Done 18.75
Time Done 19.0
Time Done 19.25
Time Done 19.5
Time Done 19.75
Time Done 20.0
Time Done 20.25
Time Done 20.5
Time Done 20.75
Time Done 21.0
Time Done 21.25
Time Done 21.5
Time Done 21.75
Time Done 22.0
Time Done 22.25
Time Done 22.5
Time Done 22.75
Time Done 23.0
Time Done 23.25
Time Done 23.5
Time Done 23.75
Day Done 6
Time Done 0
Time Done 0.25
Time Done 0.5
Time Done 0.75
Time Done 1.0
Time Done 1.25
Time Done 1.5
Time Done 1.75
Time Done 2.0
Time Done 2.25
Time Done 2.5
Time Done 2.75
Time Done 3.0
Time Done 3.25
Time Done 3.5
Time Done 3.75
Time Done 4.0
Time Done 4.25
Time Done 4.5
Time Done 4.75
Time Done 5.0
Time Done 5.25
Time Done 5.5
Time Done 5.75
Time Done 6.0
Time Done 6.25
Time Done 6.5
Time Done 6.75
Time Done 7.0
Time Done 7.25
Time Done 7.5
Time Done 7.75
Time Done 8.0
Time Done 8.25
Time Done 8.5
Time Done 8.75
Time

Time Done 9.5
Time Done 9.75
Time Done 10.0
Time Done 10.25
Time Done 10.5
Time Done 10.75
Time Done 11.0
Time Done 11.25
Time Done 11.5
Time Done 11.75
Time Done 12.0
Time Done 12.25
Time Done 12.5
Time Done 12.75
Time Done 13.0
Time Done 13.25
Time Done 13.5
Time Done 13.75
Time Done 14.0
Time Done 14.25
Time Done 14.5
Time Done 14.75
Time Done 15.0
Time Done 15.25
Time Done 15.5
Time Done 15.75
Time Done 16.0
Time Done 16.25
Time Done 16.5
Time Done 16.75
Time Done 17.0
Time Done 17.25
Time Done 17.5
Time Done 17.75
Time Done 18.0
Time Done 18.25
Time Done 18.5
Time Done 18.75
Time Done 19.0
Time Done 19.25
Time Done 19.5
Time Done 19.75
Time Done 20.0
Time Done 20.25
Time Done 20.5
Time Done 20.75
Time Done 21.0
Time Done 21.25
Time Done 21.5
Time Done 21.75
Time Done 22.0
Time Done 22.25
Time Done 22.5
Time Done 22.75
Time Done 23.0
Time Done 23.25
Time Done 23.5
Time Done 23.75
Day Done 12
Time Done 0
Time Done 0.25
Time Done 0.5
Time Done 0.75
Time Done 1.0
Time Done 1.25
Time D

In [63]:
# Extracting information by time-stamp to get features by timestamp
# Create list, then keep appending to it to form a list of lists

oneHot_y_time_col = oneHot_time_y.columns.to_list() # artificial df columns to list

testY_masterList = []

timeIndex = 0.0
timeIndex = 0
#dataIndex = 0

while(timeIndex < 1.25): # to parse every timestamp possible   
    subListY = [0]*len(oneHot_time_x.T.columns)
    df_short = df_y[df_y.timestamp_float == timeIndex]
    for row in df_short.itertuples():        
        indexCol = oneHot_geohash_col.index(row.geohash6)
        elemY = row.demand

        subListY[indexCol] = elemY

        #oneHot_transposed.at[indexCol,indexRow] = row.demand
    print("Time Done", timeIndex)
    timeIndex += 0.25
    testY_masterList.append(subListY)

Time Done 0
Time Done 0.25
Time Done 0.5
Time Done 0.75
Time Done 1.0


#### Putting it into a DF to verify our matrix manipulation

In [79]:
df_x_final = pd.DataFrame(testX_masterList, columns=oneHot_geohash_col)
df_x_final = df_x_final.T
df_x_final.columns = oneHot_x_time_col

df_x_final.tail()
df_x_final.shape

(1329, 1344)

In [81]:
df_y_final = pd.DataFrame(testY_masterList, columns=oneHot_geohash_col)
df_y_final = df_y_final.T
df_y_final.columns = oneHot_y_time_col

df_y_final.tail()
df_y_final.shape

(1329, 5)

In [68]:
# To double check our inputs
indexToCheck = 'qp0dnn'

check1 = df_x[df_x['geohash6'] == indexToCheck].sort_values(['day', 'timestamp_float'], ascending=[1, 1])
check2 = df_x_final.loc[indexToCheck , : ]
# Drop the 0 values
check2 = check2[check2 > 0]
print(check2.values)
print(check1.demand.values)
check2.values == check1.demand.values

[0.02399747 0.00551656 0.00491003 0.00398772 0.0099234  0.00429513
 0.00589814 0.00647071 0.00452769 0.00332815 0.00645709 0.00744352
 0.00388246 0.00980461 0.00455608 0.00574711 0.00053721 0.00318945]
[0.02399747 0.00551656 0.00491003 0.00398772 0.0099234  0.00429513
 0.00589814 0.00647071 0.00452769 0.00332815 0.00645709 0.00744352
 0.00388246 0.00980461 0.00455608 0.00574711 0.00053721 0.00318945]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [69]:
# To double check our inputs
indexToCheck = 'qp0dnj'

check1 = df_y[df_y['geohash6'] == indexToCheck].sort_values(['day', 'timestamp_float'], ascending=[1, 1])
check2 = df_y_final.loc[indexToCheck , : ]
# Drop the 0 values
check2 = check2[check2 > 0]
print(check2.values)
print(check1.demand.values)
check2.values == check1.demand.values

[0.0093806  0.00270139]
[0.0093806  0.00270139]


array([ True,  True])

Hopefully, everything checks out and we get True values for the previous 2 cells. Let us then proceed to prediction

### Prediction

In [70]:
def reshape_data(x_test, y_test):

    # Need to transpose this list to the form 1329 * 1344
    x_test = x_test.transpose()
    x_test = x_test.reshape(1329,1344)

    #drop 1st 4 columns to make it divisible by 5
    x_test = x_test[:,4:]

    #reshape it to form same shape as y
    x_test = x_test.reshape(5*1329, -1)

    # Need to transpose this list to the form 1329 * 5
    y_test = y_test.transpose()

    # Convert it to a nx1 vector for LGBM (doesn't support multi-output)
    y_test = y_test.ravel()
    
    return x_test, y_test

In [73]:
def report_results(model, x_test, y_test):
    y_pred = model.predict(x_test)
    print(y_pred)
    print(y_test)
    # cut-off
    print(np.shape(x_test))
   # Test RMSE error
    test_rmse = np.sqrt(mean_squared_error(y_test, y_pred))

   # Train fit
    test_r2 = r2_score(y_test, y_pred)


    print("Test RMSE: {:0.4f}".format(test_rmse))
    print("Test R2 score: {:0.4f}".format(test_r2))
    print("========================================================================")
    
    return test_rmse, test_r2, y_pred, y_test

In [87]:
# Load my model
loaded_model = pickle.load(open("bestModel.pickle.dat", "rb"))

x_test, y_test = reshape_data(np.array(testX_masterList), np.array(testY_masterList))

# Next, to compute mean statistics
test_rmse, test_r2, y_pred, y_test = report_results(loaded_model, x_test, y_test)

[0.00060472 0.00063911 0.00100498 ... 0.00056652 0.00055889 0.00055889]
[0. 0. 0. ... 0. 0. 0.]
(6645, 268)
Test RMSE: 0.0334
Test R2 score: 0.6841


Here, we have reached the end of our Testing.

### Post-processing

In [89]:
df_y_pred = pd.DataFrame(np.array(y_pred.reshape(1329,5)), columns=oneHot_y_time_col)
df_y_pred = df_y_pred.T
df_y_pred.columns = oneHot_geohash_col

df_y_test = pd.DataFrame(np.array(y_test.reshape(1329,5)), columns=oneHot_y_time_col)
df_y_test = df_y_test.T
df_y_test.columns = oneHot_geohash_col
df_y_test.tail()

qp02yc  qp02yf  qp02yu  qp02yv  qp02yy  qp02yz  qp02z1  qp02z3  \
(1, 0.0)      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
(1, 0.25)     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
(1, 0.5)      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
(1, 0.75)     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
(1, 1.0)      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

           qp02z4  qp02z5  ...  qp0djv  qp0djw    qp0djy  qp0dn0  qp0dn1  \
(1, 0.0)      0.0  0.0000  ...     0.0     0.0  0.000000     0.0     0.0   
(1, 0.25)     0.0  0.0006  ...     0.0     0.0  0.004056     0.0     0.0   
(1, 0.5)      0.0  0.0000  ...     0.0     0.0  0.000000     0.0     0.0   
(1, 0.75)     0.0  0.0000  ...     0.0     0.0  0.000000     0.0     0.0   
(1, 1.0)      0.0  0.0000  ...     0.0     0.0  0.008253     0.0     0.0   

           qp0dn4  qp0dn5  qp0dnh    qp0dnj  qp0dnn  
(1, 0.0)      0.0     0.0     0.0  0.000000     0.0  
(1, 0.25)     0.0     0.0     0.0  0.000000     0.0  
(1, 0.5)      0.0     0.0     0.0  0.009381     0.0  
(1, 0.75)     0.0     0.0     0.0  0.000000     0.0  
(1, 1.0)      0.0     0.0     0.0  0.002701     0.0  

[5 rows x 1329 columns]